"use client";

import Link from "next/link";
import { ArrowLeft, Check, Printer, X } from "lucide-react";

import { Button } from "@/components/ui/button";
import type { DashboardSummaryData } from "@/lib/dashboard/dashboard-summary";

const nextActions = [
  ["Add Students", "/dashboard/students/new"],
  ["Download Result Template", "/dashboard/templates"],
  ["Upload Results", "/dashboard/uploads/new"],
  ["View Parent Access", "/dashboard/parent-access"],
  ["View Analytics", "/dashboard/analytics"],
] as const;

function formatGeneratedDate(value: string) {
  return new Intl.DateTimeFormat("en", {
    dateStyle: "medium",
    timeStyle: "short",
    timeZone: "UTC",
  }).format(new Date(value));
}

export function DashboardSummaryPrint({ summary }: { summary: DashboardSummaryData }) {
  return (
    <div className="dashboard-summary-page bg-slate-100 px-4 py-6 text-slate-950 sm:px-6 lg:px-8">
      <div className="dashboard-summary-actions mx-auto mb-4 flex max-w-5xl flex-wrap items-center justify-between gap-3">
        <Button asChild variant="outline">
          <Link href="/dashboard">
            <ArrowLeft className="size-4" />
            Back to Dashboard
          </Link>
        </Button>
        <Button className="bg-orange-500 text-slate-950 hover:bg-orange-400" type="button" onClick={() => window.print()}>
          <Printer className="size-4" />
          Print / Save PDF
        </Button>
      </div>

      <article className="dashboard-summary-sheet mx-auto max-w-5xl rounded-2xl border border-slate-200 bg-white p-6 shadow-xl shadow-slate-200/70">
        <header className="flex flex-col gap-4 border-b border-slate-200 pb-5 sm:flex-row sm:items-start sm:justify-between">
          <div>
            <p className="text-xs font-bold uppercase tracking-[0.18em] text-orange-600">Gradix Dashboard Summary</p>
            <h1 className="mt-2 text-3xl font-bold tracking-tight text-slate-950">{summary.school.name}</h1>
            <p className="mt-1 text-sm text-slate-600">
              {summary.school.code ? `School Code: ${summary.school.code}` : "School Code: Not available"}
            </p>
          </div>
          <div className="rounded-xl border border-slate-200 bg-slate-50 p-4 text-sm text-slate-700">
            <p>
              <span className="font-semibold text-slate-950">Date generated:</span> {formatGeneratedDate(summary.generatedAt)}
            </p>
            <p className="mt-1">
              <span className="font-semibold text-slate-950">Generated by:</span> {summary.generatedBy}
            </p>
            <p className="mt-1 font-semibold text-orange-700">Generated by Gradix</p>
          </div>
        </header>

        <section className="mt-5 grid gap-3 sm:grid-cols-3">
          <div className="rounded-xl border border-slate-200 bg-slate-50 p-4">
            <p className="text-xs font-bold uppercase tracking-[0.14em] text-slate-500">Subscription Status</p>
            <p className="mt-2 text-lg font-bold text-slate-950">{summary.subscription.status}</p>
          </div>
          <div className="rounded-xl border border-slate-200 bg-slate-50 p-4">
            <p className="text-xs font-bold uppercase tracking-[0.14em] text-slate-500">Plan</p>
            <p className="mt-2 text-lg font-bold text-slate-950">{summary.subscription.plan}</p>
          </div>
          <div className="rounded-xl border border-slate-200 bg-slate-50 p-4">
            <p className="text-xs font-bold uppercase tracking-[0.14em] text-slate-500">Expiry Date</p>
            <p className="mt-2 text-lg font-bold text-slate-950">{summary.subscription.expiry ?? "Not set"}</p>
          </div>
        </section>

        <section className="mt-5">
          <h2 className="text-lg font-bold text-slate-950">Overview Metrics</h2>
          <div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
            {summary.metrics.map((metric) => (
              <div className="rounded-xl border border-slate-200 p-4" key={metric.label}>
                <p className="text-sm font-semibold text-slate-600">{metric.label}</p>
                <p className="mt-2 text-3xl font-bold text-slate-950">{metric.value}</p>
                <p className="mt-1 text-xs leading-5 text-slate-500">{metric.helper}</p>
              </div>
            ))}
          </div>
        </section>

        <section className="mt-5 grid gap-5 lg:grid-cols-[0.9fr_1.1fr]">
          <div>
            <div className="flex items-center justify-between gap-3">
              <h2 className="text-lg font-bold text-slate-950">Setup Progress</h2>
              <span className="rounded-full bg-orange-100 px-3 py-1 text-sm font-bold text-orange-700">
                {summary.setup.progress}% Complete
              </span>
            </div>
            <div className="mt-3 h-2 rounded-full bg-slate-100">
              <div className="h-full rounded-full bg-orange-500" style={{ width: `${summary.setup.progress}%` }} />
            </div>
            <ul className="mt-3 grid gap-2">
              {summary.setup.items.map((item) => (
                <li className="flex items-center gap-2 rounded-lg border border-slate-200 px-3 py-2 text-sm" key={item.label}>
                  <span className={item.complete ? "text-emerald-600" : "text-slate-400"}>
                    {item.complete ? <Check className="size-4" /> : <X className="size-4" />}
                  </span>
                  <span className="font-medium text-slate-800">{item.label}</span>
                </li>
              ))}
            </ul>
          </div>

          <div>
            <h2 className="text-lg font-bold text-slate-950">Recent Activity</h2>
            {summary.recentActivity.length === 0 ? (
              <div className="mt-3 rounded-xl border border-dashed border-slate-300 bg-slate-50 p-5 text-sm text-slate-600">
                No recent activity yet.
              </div>
            ) : (
              <ul className="mt-3 divide-y divide-slate-200 rounded-xl border border-slate-200">
                {summary.recentActivity.map((activity) => (
                  <li className="p-3" key={`${activity.title}-${activity.time}`}>
                    <div className="flex flex-wrap items-start justify-between gap-2">
                      <p className="font-semibold text-slate-950">{activity.title}</p>
                      <p className="text-xs font-medium text-slate-500">{activity.time}</p>
                    </div>
                    <p className="mt-1 text-sm leading-5 text-slate-600">{activity.description}</p>
                  </li>
                ))}
              </ul>
            )}
          </div>
        </section>

        <section className="mt-5">
          <h2 className="text-lg font-bold text-slate-950">Important Links / Next Actions</h2>
          <div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-5">
            {nextActions.map(([label, href]) => (
              <Link className="rounded-lg border border-slate-200 bg-slate-50 px-3 py-2 text-sm font-semibold text-slate-800" href={href} key={href}>
                {label}
              </Link>
            ))}
          </div>
        </section>

        <footer className="mt-6 border-t border-slate-200 pt-4 text-center text-xs leading-5 text-slate-500">
          <p className="font-semibold text-slate-700">Generated securely by Gradix.</p>
          <p>This summary is for internal school administration use.</p>
        </footer>
      </article>
    </div>
  );
}
