-- Gradix Phase 3.5: self-service school registration.

create or replace function public.generate_school_code()
returns text
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  candidate text;
begin
  loop
    candidate := 'GDX-' || upper(substr(encode(gen_random_bytes(3), 'hex'), 1, 4));
    exit when not exists (
      select 1
      from public.schools
      where school_code = candidate
    );
  end loop;

  return candidate;
end;
$$;

alter table public.schools
add column if not exists school_code text;

update public.schools
set school_code = coalesce(school_code, public.generate_school_code())
where school_code is null or btrim(school_code) = '';

alter table public.schools
alter column school_code set not null;

create unique index if not exists schools_school_code_key on public.schools (school_code);

create table if not exists public.registration_rate_limits (
  id bigint generated by default as identity primary key,
  ip_address text not null unique,
  attempt_count integer not null default 0,
  window_started_at timestamptz not null default now(),
  blocked_until timestamptz,
  last_email text,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

alter table public.registration_rate_limits enable row level security;
alter table public.registration_rate_limits force row level security;

create or replace function public.touch_registration_rate_limits_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists registration_rate_limits_set_updated_at
on public.registration_rate_limits;

create trigger registration_rate_limits_set_updated_at
before update on public.registration_rate_limits
for each row execute function public.touch_registration_rate_limits_updated_at();

create or replace function public.check_registration_rate_limit(source_ip text, source_email text default null)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  current_row public.registration_rate_limits%rowtype;
  window_minutes constant interval := interval '15 minutes';
  limit_count constant integer := 5;
begin
  if source_ip is null or btrim(source_ip) = '' then
    source_ip := 'unknown';
  end if;

  select * into current_row
  from public.registration_rate_limits
  where ip_address = source_ip
  for update;

  if current_row.id is null then
    insert into public.registration_rate_limits (ip_address, attempt_count, window_started_at, last_email)
    values (source_ip, 1, now(), source_email)
    on conflict (ip_address) do update
    set
      attempt_count = 1,
      window_started_at = now(),
      blocked_until = null,
      last_email = excluded.last_email,
      updated_at = now();

    return true;
  end if;

  if current_row.blocked_until is not null and current_row.blocked_until > now() then
    raise exception 'Too many registration attempts. Please wait and try again.';
  end if;

  if current_row.window_started_at < now() - window_minutes then
    update public.registration_rate_limits
    set
      attempt_count = 1,
      window_started_at = now(),
      blocked_until = null,
      last_email = source_email
    where ip_address = source_ip;

    return true;
  end if;

  if current_row.attempt_count + 1 > limit_count then
    update public.registration_rate_limits
    set
      attempt_count = current_row.attempt_count + 1,
      blocked_until = now() + window_minutes,
      last_email = source_email
    where ip_address = source_ip;

    raise exception 'Too many registration attempts. Please wait and try again.';
  end if;

  update public.registration_rate_limits
  set
    attempt_count = current_row.attempt_count + 1,
    last_email = source_email
  where ip_address = source_ip;

  return true;
end;
$$;

create or replace function public.finalize_school_registration()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  current_uid uuid := auth.uid();
  current_email text;
  current_name text;
  current_phone text;
  current_registration_type text;
  existing_profile public.users%rowtype;
  existing_school public.schools%rowtype;
  school_id uuid;
  school_code text;
  school_created boolean := false;
begin
  if current_uid is null then
    raise exception 'You must be signed in to complete registration.';
  end if;

  select
    email,
    coalesce(raw_user_meta_data->>'full_name', raw_user_meta_data->>'name', ''),
    raw_user_meta_data->>'phone',
    coalesce(raw_user_meta_data->>'registration_type', 'school_owner')
  into current_email, current_name, current_phone, current_registration_type
  from auth.users
  where id = current_uid;

  if current_email is null then
    raise exception 'Unable to determine the verified email address.';
  end if;

  select * into existing_profile
  from public.users
  where id = current_uid
  limit 1;

  if existing_profile.id is not null then
    select * into existing_school
    from public.schools
    where id = existing_profile.school_id
    limit 1;

    if existing_school.id is null then
      select * into existing_school
      from public.schools
      where email = current_email or metadata->>'registration_email' = current_email
      order by created_at asc
      limit 1;

      if existing_school.id is null then
        school_code := public.generate_school_code();

        insert into public.schools (
          name,
          slug,
          school_code,
          email,
          phone,
          country,
          subscription_status,
          subscription_plan,
          metadata
        )
        values (
          'New Gradix School',
          lower(school_code),
          school_code,
          current_email,
          current_phone,
          'Nigeria',
          'trialing',
          'starter',
          jsonb_build_object(
            'onboarding_completed', false,
            'registration_email', current_email,
            'owner_full_name', current_name,
            'owner_phone', current_phone,
            'registration_type', current_registration_type
          )
        )
        returning * into existing_school;

        school_created := true;
      end if;
    end if;

    update public.users
    set
      school_id = existing_school.id,
      role = 'admin'::public.app_role,
      full_name = coalesce(nullif(current_name, ''), current_email),
      email = current_email,
      phone = current_phone,
      is_active = true,
      metadata = jsonb_build_object(
        'registration_email', current_email,
        'registration_type', current_registration_type,
        'is_school_owner', true,
        'onboarding_completed', false
      )
    where id = current_uid;

    update auth.users
    set raw_user_meta_data = coalesce(raw_user_meta_data, '{}'::jsonb)
      || jsonb_build_object(
        'school_id', existing_school.id,
        'school_code', existing_school.school_code,
        'role', 'admin',
        'registration_completed', true,
        'registration_type', current_registration_type
      )
    where id = current_uid;

    return jsonb_build_object(
      'school_id', existing_school.id,
      'school_code', existing_school.school_code,
      'created', false,
      'onboarding_completed', coalesce((existing_school.metadata->>'onboarding_completed')::boolean, false)
    );
  end if;

  select * into existing_school
  from public.schools
  where email = current_email or metadata->>'registration_email' = current_email
  order by created_at asc
  limit 1;

  if existing_school.id is null then
  school_code := public.generate_school_code();

  insert into public.schools (
    name,
    slug,
    school_code,
    email,
    phone,
    country,
    subscription_status,
    subscription_plan,
    metadata
  )
  values (
    'New Gradix School',
    lower(school_code),
    school_code,
    current_email,
    current_phone,
    'Nigeria',
    'trialing',
    'starter',
    jsonb_build_object(
      'onboarding_completed', false,
      'registration_email', current_email,
      'owner_full_name', current_name,
      'owner_phone', current_phone,
      'registration_type', current_registration_type
    )
  )
  returning id, school_code into school_id, school_code;
  school_created := true;
  else
    school_id := existing_school.id;
    school_code := existing_school.school_code;
  end if;

  insert into public.users (
    id,
    school_id,
    role,
    full_name,
    email,
    phone,
    metadata
  )
  values (
    current_uid,
    school_id,
    'admin',
    coalesce(nullif(current_name, ''), current_email),
    current_email,
    current_phone,
    jsonb_build_object(
      'registration_email', current_email,
      'registration_type', current_registration_type,
      'is_school_owner', true,
      'onboarding_completed', false
    )
  )
  on conflict (id) do update
  set
    school_id = excluded.school_id,
    role = excluded.role,
    full_name = excluded.full_name,
    email = excluded.email,
    phone = excluded.phone,
    is_active = true,
    metadata = excluded.metadata;

  update auth.users
  set raw_user_meta_data = coalesce(raw_user_meta_data, '{}'::jsonb)
    || jsonb_build_object(
      'school_id', school_id,
      'school_code', school_code,
      'role', 'admin',
      'registration_completed', true
      , 'registration_type', current_registration_type
    )
  where id = current_uid;

  return jsonb_build_object(
    'school_id', school_id,
    'school_code', school_code,
    'created', school_created,
    'onboarding_completed', false
  );
end;
$$;

grant execute on function public.generate_school_code() to authenticated;
grant execute on function public.check_registration_rate_limit(text, text) to anon, authenticated;
grant execute on function public.finalize_school_registration() to authenticated;
